### ISSUE TITLE
initializeNumberFormatting is not there

### ISSUE THREAD

**Issue by gazialankus** [dart-lang/intl#178]
Readme.md talks about `initializeNumberFormatting` [at the end of this subsection](https://github.com/dart-lang/intl#number-formatting-and-parsing).  However, `initializeNumberFormatting` does [not exist in code](https://github.com/dart-lang/intl/search?q=initializeNumberFormatting&unscoped_q=initializeNumberFormatting). I wasn't sure what this meant, so I thought I'd file an issue instead of removing it from the readme with a PR.

**Comment by alan-knight** [comment]
Thanks. That might one day get added, if we deferred load the number data, but right now that's definitely wrong.

**Comment by alan-knight** [comment]
Fixed in 0ab279119c354879e7945dc19b81a5ea5078101f

**Comment by JssDWt** [comment]
This `initializeNumberFormatting` is still present in the readme.md on pub.dartlang.org. Perhaps update the package there to exclude this confusing section.
