### ISSUE TITLE
0.18.0, Version solving failed

### ISSUE THREAD

**Issue by bilalsammour** [dart-lang/intl#522]
**Describe the bug**
When upgrading to 0.18.0, I get the following error:

```
[APP_NAME] flutter pub get
Running "flutter pub get" in APP_NAME...                          
Because APP_NAME depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because APP_NAME depends on intl ^0.18.0, version solving failed.
pub get failed (1; So, because APP_NAME depends on intl ^0.18.0, version solving failed.)
exit code 1
```

**To Reproduce**
* Upgrade `intl` to 0.18.0.
* Run `flutter pub get`

**System info**
Can not, because `flutter pub get` failed.

**Versions**
* Flutter: 3.3.10
* environment sdk: ">=2.18.6 <3.0.0"
* flutter_localizations: sdk: flutter

**Comment by mosuem** [comment]
Thanks for posting this; the `intl` package version needs to be revved in `flutter_localizations`.

**Comment by mosuem** [comment]
See also https://github.com/flutter/flutter/pull/117305

**Comment by marcellocamara** [comment]
I have a similar issue when I tried to upgrade it to the version `1.18.0`:

```
Because firebase_auth 4.2.0 depends on firebase_auth_web ^5.2.0 which depends on intl ^0.17.0, firebase_auth 4.2.0 requires intl ^0.17.0.
So, because worldcup depends on both intl ^0.18.0 and firebase_auth 4.2.0, version solving failed.
pub get failed (1; So, because worldcup depends on both intl ^0.18.0 and firebase_auth 4.2.0, version solving failed.)
```

My config:
```
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '3.3.10'
```

**Comment by marcellocamara** [comment]
I have a similar issue when I tried to upgrade it to the version `0.18.0`:

```
Because firebase_auth 4.2.0 depends on firebase_auth_web ^5.2.0 which depends on intl ^0.17.0, firebase_auth 4.2.0 requires intl ^0.17.0.
So, because APP_NAME depends on both intl ^0.18.0 and firebase_auth 4.2.0, version solving failed.
pub get failed (1; So, because worldcup depends on both intl ^0.18.0 and firebase_auth 4.2.0, version solving failed.)
```

My config:
```
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '3.3.10'
```

**Comment by mosuem** [comment]
There seem to be some issues on the flutter side, see https://github.com/flutter/flutter/issues/117163.

**Comment by mosuem** [comment]
This seems to be fixed now!

**Comment by bilalsammour** [comment]
No, it is still.
Why is this issue closed?

**Comment by mosuem** [comment]
Are you sure? `flutter_localizations` depends on intl 0.18.0 now, so it should be fine.

**Comment by marcellocamara** [comment]
I still have this issue using `firebase_auth` with `intl`.

I'm stuck on `firebase_auth: ^4.2.2` because if I update it I get this error message: 
```
Because firebase_auth >=4.2.6 depends on firebase_auth_web ^5.2.5 which depends on intl ^0.17.0, firebase_auth >=4.2.6 requires intl ^0.17.0.
So, because futebolhoje depends on both intl ^0.18.0 and firebase_auth ^4.2.6, version solving failed.
pub get failed
```

Environment:
```
environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: '3.7.1'
```

**Comment by marcellocamara** [comment]
I still have this issue using `firebase_auth` with `intl`.

I'm stuck on `firebase_auth: ^4.2.2` because if I update it I get this error message: 
```
Because firebase_auth >=4.2.6 depends on firebase_auth_web ^5.2.5 which depends on intl ^0.17.0, firebase_auth >=4.2.6 requires intl ^0.17.0.
So, because MY_APP depends on both intl ^0.18.0 and firebase_auth ^4.2.6, version solving failed.
pub get failed
```

Environment:
```
environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: '3.7.1'
```

**Comment by bilalsammour** [comment]
Yes, this is the error
```
[APP_NAME] flutter pub get
Running "flutter pub get" in APP_NAME...
Resolving dependencies...
Because APP_NAME depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because APP_NAME depends on intl ^0.18.0, version solving failed.
pub get failed
```

**Comment by mosuem** [comment]
Maybe this is a Flutter SDK versioning thing? I am not expert on Flutter, but would expect some delay between the error being fixed on GitHub and being rolled out. @thkim1011

**Comment by Rexios80** [comment]
Does version `0.18.0` actually contain breaking changes from `0.17.0`? If not, it should have been released as `0.17.1`. The best solution to prevent this confusion in the future is to make the next release `1.0.0` so that minor version changes aren't treated as breaking by dependency resolution.

**Comment by Rexios80** [comment]
Also for anyone having issues with dependency resolution, if version `0.18.0` doesn't contain breaking changes you can just add `intl` to your `dependency_overrides`:

```yaml
dependency_overrides:
  intl: ^0.18.0
```

**Comment by mosuem** [comment]
@Rexios80: There were some minor changes to the API. The switch to `0.18.0` was also made to keep the versions of `intl` and `intl_translation` in sync, the latter being migrated to null safety, to indicate that these packages are supported and alive and well :)

Sorry for the bugs caused by this. We/I will try to avoid this in the future.

**Comment by under3415** [comment]
Hi, we cannot upgrade to the latest version of `intl`. This is still an ongoing issue. Why is this closed?

**Comment by mosuem** [comment]
Hi, this is fixed in Flutter HEAD, which is why the Flutter issue is closed. This one is still open for now.

**Comment by pavinod** [comment]
> Also for anyone having issues with dependency resolution, if version `0.18.0` doesn't contain breaking changes you can just add `intl` to your `dependency_overrides`:
> 
> ```yaml
> dependency_overrides:
>   intl: ^0.18.0
> ```

Thanks for this temporary workaround!

**Comment by under3415** [comment]
> Hi, this is fixed in Flutter HEAD, which is why the Flutter issue is closed. This one is still open for now.

What is Flutter HEAD? Is that Flutter SDK? There have been a few releases and this is still not resolved. 

I know it is unpopular asking for ETA, but do we know approximately when is this going to be resolved? 

I am not sure if I can apply an override, not sure what the implications of doing that are.

**Comment by Rexios80** [comment]
> What is Flutter HEAD?

The same thing as flutter channel master

> I know it is unpopular asking for ETA, but do we know approximately when is this going to be resolved?

Probably the next major Flutter release at the latest

> I am not sure if I can apply an override, not sure what the implications of doing that are.

The implications are your code will fail to build if any changes in `intl` actually break your dependencies. I've been running a pretty large-scale app in production with the override and haven't had any issues. If you're having issues resolving dependencies, you'll probably have better luck just using the override. The odds of bad behavior cropping up if you can build successfully are probably slim.
